typography_spectrum: 0.787951153004542
color:
  brandStrength: 0.3622462316416204
  lightness: 0.2946701890323311
  saturation: 0.8640935705043375
  rhythmicContrast: 0.6231493377126753
  brandColors:
    - '#25064D'
    - '#36175E'
    - '#553285'
    - '#7B52AB'
    - '#9768D1'
opengraph:
  image: null
layout_spectrum: 0.4510746952146292
analytics:
  google: UA-78600613-3
author:
  name: Maurine Dodge Photography
  email: silvatungfox@gmail.com
  url: 'http://maurinedodgephotography.com/'
name: Gypsy Maiden
navigation:
  - name: Gypsy Maiden on Facebook
    url: 'https://www.facebook.com/gypsymaidenproject/?fref=ts'
    type: external
title: The Gypsy Maiden Project
